name: Build checks

on:
  push:
    branches: [ "main", "template-dev" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release, Debug

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "MSVC Debug"
          os: windows-latest
          build_type: "Debug"
          unity: OFF
          double_precision: OFF
        - name: "MSVC Debug Unity"
          os: windows-latest
          build_type: "Debug"
          unity: ON
          double_precision: OFF
        - name: "MSVC Release"
          os: windows-latest
          build_type: "Release"
          unity: OFF
          double_precision: OFF
        - name: "MSVC Release Unity"
          os: windows-latest
          build_type: "Release"
          unity: ON
          double_precision: OFF
        - name: "MSVC Debug Double Precision"
          os: windows-latest
          build_type: "Debug"
          unity: OFF
          double_precision: ON
        - name: "MSVC Debug Unity Double Precision"
          os: windows-latest
          build_type: "Debug"
          unity: ON
          double_precision: ON
        - name: "MSVC Release Double Precision"
          os: windows-latest
          build_type: "Release"
          unity: OFF
          double_precision: ON
        - name: "MSVC Release Unity Double Precision"
          os: windows-latest
          build_type: "Release"
          unity: ON
          double_precision: ON
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DMATH_UNITY=${{matrix.config.unity}} -DMATH_SANITIZER=OFF -DMATH_REAL_AS_DOUBLE=${{matrix.config.double_precision}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{matrix.config.build_type}}

