name: Build checks

on:
  push:
    branches: [ "main", "template-dev" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release, Debug

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "MSVC Debug"
          os: windows-latest
          build_type: "Debug"
          shared_libs: OFF
        - name: "MSVC Release"
          os: windows-latest
          build_type: "Release"
          shared_libs: OFF
        - name: "MSVC Debug Shared"
          os: windows-latest
          build_type: "Debug"
          shared_libs: ON
        - name: "MSVC Release Shared"
          os: windows-latest
          build_type: "Release"
          shared_libs: ON
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DMATH_HARDENING=OFF -DMATH_SHARED_LIBS=${{matrix.config.shared_libs}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install-dir --config ${{matrix.config.build_type}}

    - name: Test
      run: ${{github.workspace}}/install-dir/bin/math_test.exe

